MVC Website C#/Mooshak2.0/Mooshak2.0/Models/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mooshak2._0.Models.ViewModels
{
    public class UserViewModel
    {

        public string ID { get; set; }
        [Required]
        public string UserName { get; set; }
        public string Role { get; set; }
        public int CourseId { get; set; }
        public bool IsSelected { get; set; }
        public List<CourseViewModel> Courses { get; set; }
        public List<SelectListItem> CourseList { get; set; }



    }
}

MVC Website C#/Mooshak2.0/Mooshak2.0/Controllers/AssignmentController.cs
using Microsoft.AspNet.Identity;
using Mooshak2._0.Models.ViewModels;
using Mooshak2._0.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.AccessControl;
using System.Web;
using System.Web.Mvc;



namespace Mooshak2._0.Controllers
{
    public class AssignmentController : Controller
    {
        private TeacherService TS = new TeacherService();
        private UserService US = new UserService(null);
        private AssignmentService AS = new AssignmentService(null);
        private SubmissionService SS = new SubmissionService(null);
        private LevenshteinService LS = new LevenshteinService();

        private string RootDir = AppDomain.CurrentDomain.BaseDirectory;
        private string UserDataDir = AppDomain.CurrentDomain.BaseDirectory + @"\userdata";

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult CreateAssignment(int? CourseID)
        {
            if(CourseID != null)
            {
                if(!AS.CourseExist(CourseID))
                {
                    throw new Exception();
                }
            }
            var AssignmentViewModel = new AssignmentViewModel();
            AssignmentViewModel.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), CourseID);
            return View(AssignmentViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult CreateAssignment(AssignmentViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);

            if (ModelState.IsValid)
            {
                ModelState.Clear();
                int AssID = TS.CreateAssignment(model);
                model = TS.UploadAssignmentFiles(AssID, model, files);
                return RedirectToAction("StudentAssignments", "User", new { id = AssID });
            }
            return View(model);
        }
        /// <summary>
        /// Teacher creates a new milestone for assignment
        /// sends in .zip with the program (main.cpp) and .txt with input if there is any.
        /// gets in return values from the compiler.
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult CreateMilestone(MilestoneViewModel model, HttpPostedFileBase ZipFile, HttpPostedFileBase TxtFile)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                int MileID = TS.CreateMilestone(model);
                model.ID = MileID;
                if (ZipFile != null)
                {
                    var ZipType = "zip";
                    var TextType = "txt";

                    var ZipEnding = System.IO.Path.GetExtension(ZipFile.FileName).Substring(1);
                    if (!ZipType.Contains(ZipEnding))
                    {
                        ViewBag.Output = "Error: upload approriate .zip file";
                        model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
                        return View(model);
                    }
                    if (TxtFile != null)
                    {
                        var TextEnding = System.IO.Path.GetExtension(TxtFile.FileName).Substring(1);
                        if (!TextType.Contains(TextEnding))
                        {
                            ViewBag.Output = "Error: upload approriate .txt file";
                            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
                            return View(model);
                        }
                    }
                    Stopwatch watch = new Stopwatch();
                    watch.Start();

                    try
                    {
                        model = TS.CompileMilestoneUpload(model, ZipFile, TxtFile);
                    }
                    catch
                    {
                        //return error, compile failed, invalid file?
                        throw new Exception();
                    }

                    watch.Stop();
                    TimeSpan ts = watch.Elapsed;
                    ViewBag.Output = "Compiled in " + ts.Seconds + "." + ts.Milliseconds / 10 + " seconds";

                    TS.EditMilestone(model);
                }
            }
            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult CreateMilestone(int AssignmentID, int? CourseID)
        {
            if(AS.GetAssignmentByID(AssignmentID) == null)
            {
                throw new Exception();
            }
            if (CourseID != null)
            {
                if (!AS.CourseExist(CourseID))
                {
                    throw new Exception();
                }
            }
            var ViewModel = new MilestoneViewModel();
            ViewModel.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), CourseID);
            return View(ViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult EditAssignment(int AssignmentID)
        {
            var Assignment = AS.GetAssignmentByID(AssignmentID);
            Assignment.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), Assignment.CourseID);
            Assignment.UserDataLinks = TS.GetAssignmentLinks(Assignment);
            return View(Assignment);
        }

        public ActionResult RemoveFile(string FilePath)
        {
            TS.DeleteAssignmentFile(FilePath);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult EditAssignment(AssignmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                TS.EditAssignment(model);
                return RedirectToAction("StudentAssignments", "User", new { id = model.ID });
            }
            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
            return View(model);
        }


        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult EditMilestone(int MilestoneID)
        {
            var Milestone = AS.GetMilestoneByID(MilestoneID);
            Milestone.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), Milestone.CourseID);
            return View(Milestone);
        }
        /// <summary>
        /// Teacher edits current milestone for assignment
        /// sends in .zip with the program (main.cpp) and .txt with input if there is any.
        /// gets in return values from the compiler.
        /// </summary>
        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult EditMilestone(MilestoneViewModel model, HttpPostedFileBase ZipFile, HttpPostedFileBase TxtFile)
        {
            if (ModelState.IsValid)
            {
                ModelState.Clear();
                if (ZipFile != null)
                {
                    var ZipType = "zip";
                    var TextType = "txt";

                    var ZipEnding = System.IO.Path.GetExtension(ZipFile.FileName).Substring(1);
                    if (!ZipType.Contains(ZipEnding))
                    {
                        ViewBag.Output = "Error: upload approriate .zip file";
                        model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
                        return View(model);
                    }
                    if(TxtFile != null)
                    {
                        var TextEnding = System.IO.Path.GetExtension(TxtFile.FileName).Substring(1);
                        if (!TextType.Contains(TextEnding))
                        {
                            ViewBag.Output = "Error: upload approriate .txt file";
                            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
                            return View(model);
                        }
                    }
                    Stopwatch watch = new Stopwatch();
                    watch.Start();

                    try
                    {
                        model = TS.CompileMilestoneUpload(model, ZipFile, TxtFile);
                    }
                    catch
                    {
                        //return error, compile failed, invalid file?
                        throw new Exception();
                    }

                    watch.Stop();
                    TimeSpan ts = watch.Elapsed;
                    ViewBag.Output = "Compiled in " + ts.Seconds + "." + ts.Milliseconds / 10 + " seconds";
                }
                TS.EditMilestone(model);
            }
            model.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), model.CourseID);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult DeleteAssignment(int AssID, int? CourseID)
        {
            TS.DeleteAssignment(AssID);
            return RedirectToAction("TeacherHome", "User", new { id = CourseID });
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult DeleteMilestone(int MileID, int CourseID)
        {
            TS.DeleteMilestone(MileID);
            return RedirectToAction("TeacherHome", "User", new { id = CourseID });
        }
        /// <summary>
        /// Student sends in a solution to a milestone
        /// This function contancts studentcompile which uses the compiler

MVC Website C#/Mooshak2.0/Mooshak2.0/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mooshak2._0.Services;
using Microsoft.AspNet.Identity;
using Mooshak2._0.Models.ViewModels;

namespace Mooshak2._0.Controllers
{
    public class UserController : Controller
    {
        private UserService US = new UserService(null);
        private AssignmentService AS = new AssignmentService(null);
        private SubmissionService SS = new SubmissionService(null);
        private TeacherService TS = new TeacherService();

        [Authorize(Roles = "Students, Teachers")]
        public ActionResult StudentHome(int? id)
        {
            var ViewModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), id);

            if(ViewModel.Submissions != null)
            {
                foreach (var m in ViewModel.Submissions)
                {
                    m.AssignmentName = AS.GetAssignmentByID(m.AssignmentID).Name;
                }
            }

            if(ViewModel.Assignments != null)
            {
                foreach (var ass in ViewModel.Assignments)
                {
                    var submissions = ViewModel.Submissions.Where(x => x.AssignmentID == ass.ID).ToList();
                    ass.Grade = AS.GetGradeForAssignment(ass.Milestones, submissions);
                }
            }

            return View(ViewModel);
        }

        [Authorize(Roles = "Students, Teachers")]
        public ActionResult StudentAssignments(int id)
        {
            var AssignmentViewModel = AS.GetAssignmentByID(id);
            if(AssignmentViewModel == null)
            {
                throw new Exception();
            }
            AssignmentViewModel.UserDataLinks = TS.GetAssignmentLinks(AssignmentViewModel);
            AssignmentViewModel.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), AssignmentViewModel.CourseID);
            AssignmentViewModel.UserModel.AssignmentID = id;
            return View(AssignmentViewModel);
        }
        /// <summary>
        /// Returns all student milestones for submission
        /// </summary>
        [Authorize(Roles = "Students, Teachers")]
        public ActionResult StudentMilestones(int id, int? SubID)
        {
            var MilestoneViewModel = AS.GetMilestoneByID(id);
            if(MilestoneViewModel == null)
            {
                throw new Exception();
            }
            var AssignmentViewModel = AS.GetAssignmentByID(MilestoneViewModel.AssignmentID);
            MilestoneViewModel.UserDataLinks = TS.GetMilestoneLinks(MilestoneViewModel, User.Identity.GetUserName());
            MilestoneViewModel.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), AssignmentViewModel.CourseID);
            MilestoneViewModel.Users = TS.GetAllStudentsInCourse(AssignmentViewModel.CourseID);
            MilestoneViewModel.Submissions = TS.GetSubmissionsInMilestone(MilestoneViewModel.ID);

            if(SubID == null)
            {
                try
                {
                    MilestoneViewModel.SubmissionID = MilestoneViewModel.UserModel.Submissions.Where(x => x.MilestoneID == id).FirstOrDefault().ID;
                }
                catch { }
            }
            else
            {
                MilestoneViewModel.SubmissionID = SubID;
            }
            MilestoneViewModel.UserModel.AssignmentID = MilestoneViewModel.AssignmentID;
            return View(MilestoneViewModel);
        }

        [Authorize(Roles = "Teachers")]
        public ActionResult TeacherHome(int? id)
        {
            var ViewModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), id);

            return View(ViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult TeacherComment(SubmissionViewModel sub)
        {
            if(!ModelState.IsValid)
            {
                sub.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), sub.CourseID);
                return View(sub);
            }
            TS.TeacherComment(sub.Comment, sub.ID, sub.Grade);
            return RedirectToAction("StudentMilestones", "User", new { id = sub.MilestoneID });
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult TeacherComment(int subID)
        {
            var sub = SS.GetSubmissionByID(subID);
            sub.UserModel = US.GetUserOverviewByUserName(User.Identity.GetUserName(), sub.CourseID);
            return View(sub);
        }
    }
}

MVC Website C#/Mooshak2.0/Mooshak2.0/Views/User/StudentAssignments.cshtml
@model Mooshak2._0.Models.ViewModels.AssignmentViewModel


@{
    ViewBag.Title = "StudentAssignments";
}
<div class="main-view">
    @Html.Partial("UserMain", Model.UserModel)

    <div class="col-sm-8 col-md-10 middle">
        <div class="main-content">
            <h2>@Model.Name</h2>

            @if (User.IsInRole("Teachers"))
            {
                @Html.ActionLink("Edit Assignment", "EditAssignment", "Assignment", new { AssignmentID = Model.ID }, new { @class = "Milestones btn btn-default" })
            }

            <h4>Due Date: @Model.DueDate</h4>

            @if (Model.UserDataLinks != null)
            {
                <h3>Assignment Files</h3>
                <ul class="list-unstyled">
                    @foreach (var file in Model.UserDataLinks)
                    {
                        <li>
                            <a href="@file">@file.Split('\\').LastOrDefault()</a>
                        </li>

                    }
                </ul>
            }
            <h3>Milestones</h3>
            <table class="overall-column table table-striped border-table">
                
                <tbody>
                    @foreach (var milestone in Model.Milestones)
                    {

                        <tr>
                            <td class="table-left">@milestone.Name</td>
                            <td>@Html.ActionLink("View", "StudentMilestones", "User", new { id = milestone.ID }, new { @class = "btn" })</td>
                        </tr>

                    }
                    @if(User.IsInRole("Teachers"))
                    {
                        <tr>
                            <td>Create New Milestone</td>
                            <td><a href="@Url.Action("CreateMilestone", "Assignment", new { AssignmentID = Model.ID, CourseID = Model.CourseID }, null)"><i class="glyphicon glyphicon-plus"></i></a> </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>

</div>

MVC Website C#/Mooshak2.0/Mooshak2.0/Views/User/StudentHome.cshtml
@model Mooshak2._0.Models.ViewModels.UserHomeViewModel
@{
    ViewBag.Title = "StudentHome";
}
<div class="main-view">

    @Html.Partial("UserMain")

    <div class="col-sm-7 col-md-8 middle">
        <div class="main-content">
            <h2>Home</h2>
            <h3>Welcome to Mooshak 2.0</h3>
            <p>Welcome @User.Identity.Name.Split('@').FirstOrDefault()</p>
        </div>
        <div class="nextAssignments">
            <table class="overall-column table-striped border-table">
                <thead class="AssignmentsBox">
                    <tr>
                        <th>Next Assignments</th>
                        <th>Due Date</th>
                    </tr>
                </thead>
                <tbody class="assignments">
                    @if (Model.Assignments != null)
                    {
                        foreach (var assignment in Model.Assignments)
                        {
                            var Start = assignment.StartDate;
                            var Due = assignment.DueDate;
                            var Now = DateTime.Now;
                            if (Start < Now && Due > Now)
                            {
                                <tr>
                                    <td>@Html.ActionLink(assignment.Name, "StudentAssignments", "User", new { id = assignment.ID }, null)</td>
                                    <td>@assignment.DueDate</td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-1 col-md-2 secondSidebar">
        <h3>Grades</h3>
        <table class="table table-striped border-table">
            <thead class="AssignmentsBox">
                <tr>
                    <th>Assignment</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody class="assignments">
                @if (Model.Assignments != null)
                {
                    foreach (var assignments in Model.Assignments)
                    {
                        var Start = assignments.StartDate;
                        var Now = DateTime.Now;
                        if (Start < Now)
                        {
                            <tr>
                                <td>@assignments.Name</td>
                                <td>@assignments.Grade</td>
                            </tr>
                        }
                    }
                }
            </tbody>
        </table>
        <div class="averageGrade">
            @if (Model.Assignments != null)
            {
                var Count = 0;
                var AverageGrade = 0.0;
                foreach (var assignment in Model.Assignments)
                {
                    var Due = assignment.DueDate;
                    var Now = DateTime.Now;
                    if (Due < Now)
                    {
                        AverageGrade += assignment.Grade;
                        Count++;
                    }
                }
                AverageGrade = AverageGrade / Count;
                <h4 id="averageGrade">Average Grade: @AverageGrade</h4>
            }
        </div>

    </div>
</div>

MVC Website C#/Mooshak2.0/Mooshak2.0/Views/User/TeacherComment.cshtml
@model Mooshak2._0.Models.ViewModels.SubmissionViewModel

@{
    ViewBag.Title = "TeacherComment";
}
<div class="main-view">
    @Html.Partial("UserMain", Model.UserModel)
    <div class="col-sm-7 col-md-8 middle">
        <div class="main-content">
            <h2>Comment and grade</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.MilestoneID)
                    @Html.HiddenFor(model => model.CourseID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Comment, new { @class = "descriptionWindow" })
                            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

MVC Website C#/Mooshak2.0/Mooshak2.0/Views/User/TeacherHome.cshtml
@model Mooshak2._0.Models.ViewModels.UserHomeViewModel

<div class="main-view">

    @Html.Partial("UserMain")

    <div class="col-sm-7 col-md-8 middle">
        <div class="main-content">
            <h2>Home</h2>
            <h3>Welcome to Mooshak 2.0</h3>
            <p>Welcome @User.Identity.Name.Split('@').FirstOrDefault()</p>
        </div>
        <div class="nextAssignments">
            <table class="table-hover overall-column table table-striped border-table">
                <thead>
                    <tr>
                        <th>Next Assignments</th>
                        <th>Start Date</th>
                        <th>Due Date</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    @if(Model.Assignments != null)
                    {
                        foreach (var assignment in Model.Assignments)
                        {
                            var Start = assignment.StartDate;
                            var Due = assignment.DueDate;
                            var Now = DateTime.Now;
                            if (Start < Now && Due > Now)
                            {
                                <tr>
                                    <td>@Html.ActionLink(assignment.Name, "StudentAssignments", "User", new { id = assignment.ID }, null)</td>
                                    <td>@Start</td>
                                    <td>@Due</td>
                                    <td>@Html.ActionLink("Edit", "EditAssignment", "Assignment", new { AssignmentID = assignment.ID }, null)</td>
                                </tr>
                            }
                        }
                    }
                
                </tbody>
            </table>
        </div>
    </div>
</div>

MVC Website C#/Mooshak2.0/Mooshak2.0/Views/User/UserMain.cshtml
@model Mooshak2._0.Models.ViewModels.UserHomeViewModel

<div class="col-sm-1 col-md-2 sidebar">
    <div class="dropdown">
        <button class="btn selected">@Model.CourseName<i class="glyphicon glyphicon-menu-down"></i></button>
        <div class="dropdown-content">
                @if (User.IsInRole("Students"))
                {
                    foreach (var course in Model.Courses)
                    {
                        @Html.ActionLink(course.Name, "StudentHome", "User", new { id = course.ID }, null);
                    }
                }
                else
                {
                    foreach (var course in Model.Courses)
                    {
                        @Html.ActionLink(course.Name, "TeacherHome", "User", new { id = course.ID }, null);
                    }
                }
        </div>
    </div>
    <ul class="nav ulBar">
        <div class="AssignmentsBox">
            <h4>Assignments</h4>
        </div>
        @if (Model.Assignments != null)
        {
            foreach (var assignment in Model.Assignments)
            {
            <li>
                @if ((assignment.StartDate <= DateTime.Now  && assignment.Hidden == false)|| User.IsInRole("Teachers"))
                {
                    @Html.ActionLink(assignment.Name, "StudentAssignments", "User", new { id = assignment.ID }, new { @class = "assignments" })
                    <ul class="milestones">
                            @foreach (var milestone in assignment.Milestones)
                            {
                                
                                if (milestone.AssignmentID == Model.AssignmentID)
                                {
                                    <li>
                                        @Html.ActionLink(milestone.Name, "StudentMilestones", "User", new { id = milestone.ID }, new { @class="milestone"})
                                    </li>
                                    
                                }

                            }
                        @if (User.IsInRole("Teachers") && assignment.ID == Model.AssignmentID)
                        {
                            <li>
                                @Html.ActionLink("New Milestone ", "CreateMilestone", "Assignment", new { AssignmentID = assignment.ID, CourseID = assignment.CourseID }, new { @class = "milestone" })<i class="glyphicon glyphicon-plus smallicon"></i>
                            </li>
                        }                       
                    </ul>
                }
            </li>
            }
        }

        @if (User.IsInRole("Teachers") && Model.Courses.Count() > 0)
        {
            <li>
                <a href="@Url.Action("CreateAssignment", "Assignment", new { CourseID = Model.CourseID }, null)" class="assignments">New Assignment <i class="glyphicon glyphicon-plus smallicon"></i></a>
            </li>
        }
    </ul>
</div>